/**:
  ros__parameters:
    system_id: 255
    plugin_denylist:
      # common
      - '*'

    plugin_allowlist:
      - 'sys_*'
      - 'imu'
      - 'rc_io'
      - 'param'
      - 'command'
      - 'local_position'
      - 'setpoint_position'
      - 'vision_pose'
